import '../styles/globals.css';
import { appWithTranslation } from 'next-i18next';
import Head from 'next/head';
import Script from 'next/script';
import Navbar from './Navbar';
import nextI18NextConfig from '../next-i18next.config';
import Footer from './Footer';
import BackToTopButton from '../components/BackToTopButton'; // Import BackToTopButton

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>AsadTech</title>
        <meta name="description" content="Agency Website - Generated by AsadTech" />
        {/* bootstrap css cdn */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      {/* bootstrap js cdn */}
      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous"
      ></Script>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
      <BackToTopButton /> {/* Add the BackToTopButton here */}
    </>
  );
}

export default appWithTranslation(MyApp, nextI18NextConfig);
